spring.application.name=derivatrade
spring.datasource.url=jdbc:postgresql://localhost:5432/derivatrade
spring.datasource.username=niraj
spring.datasource.passowrd=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled-=true
spring.flyway.validate-migration-naming=true